#!/bin/tcsh

#Created by Mike Iacono, November 2003
#This script links two source files from the RRTM_LW local_version
#directory to this src directory.

ln -s /storm/rc1/rrtm_lw_local_version/src/extra.f .
ln -s /storm/rc1/rrtm_lw_local_version/src/rrtatm.f .


